/**
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext;

import com.city.network.xtext.AbstractCityDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CityDslRuntimeModule extends AbstractCityDslRuntimeModule {
}
