/**
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.validation;

import com.city.network.xtext.validation.AbstractCityDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CityDslValidator extends AbstractCityDslValidator {
}
