/**
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.scoping;

import com.city.network.xtext.scoping.AbstractCityDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CityDslScopeProvider extends AbstractCityDslScopeProvider {
}
