/*
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.parser.antlr;

import com.city.network.xtext.parser.antlr.internal.InternalCityDslParser;
import com.city.network.xtext.services.CityDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CityDslParser extends AbstractAntlrParser {

	@Inject
	private CityDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCityDslParser createParser(XtextTokenStream stream) {
		return new InternalCityDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "City";
	}

	public CityDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CityDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
