/**
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.ide;

import com.city.network.xtext.ide.AbstractCityDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CityDslIdeModule extends AbstractCityDslIdeModule {
}
