/*
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class CityDslUiModule extends AbstractCityDslUiModule {
}
