/*
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CityDslStandaloneSetup extends CityDslStandaloneSetupGenerated {

	def static void doSetup() {
		new CityDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
