/*
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CityDslRuntimeModule extends AbstractCityDslRuntimeModule {
}
