/**
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.ui.contentassist;

import com.city.network.xtext.ui.contentassist.AbstractCityDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CityDslProposalProvider extends AbstractCityDslProposalProvider {
}
