/**
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext;

import com.city.network.xtext.CityDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CityDslStandaloneSetup extends CityDslStandaloneSetupGenerated {
  public static void doSetup() {
    new CityDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
