/*
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.ui.tests;

import com.city.network.xtext.ui.internal.XtextActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CityDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("com.city.network.xtext.CityDsl");
	}

}
