/*
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCityDslScopeProvider extends DelegatingScopeProvider {
}
