/**
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.ui;

import com.city.network.xtext.ui.AbstractCityDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CityDslUiModule extends AbstractCityDslUiModule {
  public CityDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
