/**
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.formatting2;

import com.city.network.Line;
import com.city.network.MCity;
import com.city.network.Station;
import com.city.network.xtext.services.CityDslGrammarAccess;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class CityDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private CityDslGrammarAccess _cityDslGrammarAccess;
  
  protected void _format(final MCity city, @Extension final IFormattableDocument document) {
    EList<Station> _stations = city.getStations();
    for (final Station station : _stations) {
      document.<Station>format(station);
    }
    EList<Line> _lines = city.getLines();
    for (final Line line : _lines) {
      document.<Line>format(line);
    }
  }
  
  public void format(final Object city, final IFormattableDocument document) {
    if (city instanceof MCity) {
      _format((MCity)city, document);
      return;
    } else if (city instanceof XtextResource) {
      _format((XtextResource)city, document);
      return;
    } else if (city instanceof EObject) {
      _format((EObject)city, document);
      return;
    } else if (city == null) {
      _format((Void)null, document);
      return;
    } else if (city != null) {
      _format(city, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(city, document).toString());
    }
  }
}
