/**
 * generated by Xtext 2.15.0
 */
package com.city.network.xtext.ide;

import com.city.network.xtext.CityDslRuntimeModule;
import com.city.network.xtext.CityDslStandaloneSetup;
import com.city.network.xtext.ide.CityDslIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class CityDslIdeSetup extends CityDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    CityDslRuntimeModule _cityDslRuntimeModule = new CityDslRuntimeModule();
    CityDslIdeModule _cityDslIdeModule = new CityDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_cityDslRuntimeModule, _cityDslIdeModule));
  }
}
